### PR TITLE
Fix reference to definitions.units

### PR DESCRIPTION
**Pull request by rartino**
Apparently I missed an 's' on definitions.units when I wrote the section for readme.md.
This probably should be fixed before release.

### CODE REVIEW

**Review by ml-evs — DISMISSED** [review]

**Comment by JPBergsma** [comment]
In optimade.rst there are also two references to definition.units (lines 2122 and 2136). Should these be fixed as well?

**Review by merkys — CHANGES_REQUESTED** [review]
@JPBergsma is right, there are more occurrences needing replacement.

**Comment by rartino** [comment]
@JPBergsma @merkys Ok, done. Thanks for checking.

**Review by ml-evs — APPROVED** [review]

**Review by JPBergsma — APPROVED** [review]
LGTM

**Comment by rartino** [comment]
@merkys you have an outstanding change request that blocks this merge (and I think it is addressed).

**Review by merkys — APPROVED** [review]
Right, all good now!

**Pull request merged**
