### PR TITLE
Updated: allow web-browsers to issue cross-domain requests

### LINKED ISSUE #101: Allow web-browsers to issue cross-domain requests
This only concerns JavaScript requests done from the web-browsers via **XMLHttpRequest** and **ActiveXObject**. By default the web-browsers are not allowed to fetch content from an OPTiMaDe server, living on an external domain, unless such header is included into the server's response:

`Access-Control-Allow-Origin: *`

May I kindly ask you to include this header into your server implementation responses.

### PR DESCRIPTION
**Pull request by rartino**
I don't dare to merge the original PR #105 since it shows a diff that is the whole file.

So, here is a PR rebased on the latest devel that shows a sane diff. I also *slightly* reworded the phrasing in a way I hope is uncontroversial. 

Closes #105, closes #101.

### CODE REVIEW

**Comment by merkys** [comment]
I still feel there's a need to include at least one of [RFC 2119 keywords](http://tools.ietf.org/html/rfc2119) to let the adopters know how strong this paragraph is. (I suspect `MAY/OPTIONALLY` is needed here)

**Comment by rartino** [comment]
@merkys The whole point in the discussion in #105 was that what we could come to an agreement on is to leave this as an implementors note and not a statement of conformity to the standard.

My intent is that in the hypotetical conversion to RST after the release of v0.10 we separate out implementors notes from the specification with this markup: https://github.com/rartino/OPTiMaDe/blob/restructuredtext/demo.rst#15notes

**Comment by merkys** [comment]
Sorry, I didn't follow the discussion on #105 to the end. I suppose we can add it for now then.

**Comment by rartino** [comment]
That addition was @fawzi's request. @fawzi, what are your thoughts?

**Comment by fawzi** [comment]
The idea was that if we explain the issue an solutions, I would explain things neutrally, and for paranoids listing only one site is an option, but I do not feel strongly about it.

**Comment by rartino** [comment]
I've tried my best to rectify the final concerns. Is the present version acceptable?

**Comment by rartino** [comment]
Since the opinions expressed about `Access-Control-Allow-Origin: <site-of-the-javascript-page>` both come with "not very import", and we have 3 approvals, I'm going to merge this. Still, we may want to revisit to this question for v1.0.

**Pull request merged**
