### PR TITLE
[ON-HOLD] Staging of v1.0.1 release

### PR DESCRIPTION
**Pull request by ml-evs**
This PR backports recent changes from develop ready for the patch release of v1.0.1. It includes all commits to `develop` since v1.0.0, except the addition of the `issue_tracker` field in #339, plus a commit that adjusts the version number in the specification document (a corresponding commit will need to be made in develop to update the version to `v1.0.1~develop` or `v1.1.0~develop`.

This should not be merged/released until all other open PRs that match the v1.0.1 milestone have been merged: https://github.com/Materials-Consortia/OPTIMADE/milestone/5

### CODE REVIEW

**Comment by CasperWA** [comment]
Let's maybe push this through now to patch v1.0? It doesn't matter if v1.1 is coming up soon, patching v1.0 is still very valuable.

**Comment by ml-evs** [comment]
> Let's maybe push this through now to patch v1.0? It doesn't matter if v1.1 is coming up soon, patching v1.0 is still very valuable.

Agreed! I just need to remake this PR with the new commits to develop.

**Comment by CasperWA** [comment]
Rebase + ready for review :)

**Comment by ml-evs** [comment]
> Rebase + ready for review :)

It's a bit tricky as I have to rebase and exlude the issue_tracker PR commits, so I will do this in the session later on...

**Comment by ml-evs** [comment]
Started preparing this PR again and had a bad thought... GitHub maps commits to PRs via their hash, and the necessary cherry-picking we have to do here breaks that connection (and hence the connection to the discussions and issues around a PR). This is fine when the PR number has been included in the commit title (as is done automatically for squashes), but is not the case for multi-commit PRs. 

Do we care about this? I could add PR numbers to all of the commit messages as part of the rebase?

**Comment by CasperWA** [comment]
> Started preparing this PR again and had a bad thought... GitHub maps commits to PRs via their hash, and the necessary cherry-picking we have to do here breaks that connection (and hence the connection to the discussions and issues around a PR). This is fine when the PR number has been included in the commit title (as is done automatically for squashes), but is not the case for multi-commit PRs.

How much cherry-picking do we need to do? :/

> Do we care about this? I could add PR numbers to all of the commit messages as part of the rebase?

Hmm... I really wouldn't. The SHAs are still unique and defining in themselves, no?
And the PRs are still there if one needs to dig through them. It should still be more efficient to search through them using GH's search functionality than referencing a commit SHA? Or?

**Comment by CasperWA** [comment]
> > > Started preparing this PR again and had a bad thought... GitHub maps commits to PRs via their hash, and the necessary cherry-picking we have to do here breaks that connection (and hence the connection to the discussions and issues around a PR). This is fine when the PR number has been included in the commit title (as is done automatically for squashes), but is not the case for multi-commit PRs.
> > 
> > 
> > How much cherry-picking do we need to do? :/
> > > Do we care about this? I could add PR numbers to all of the commit messages as part of the rebase?
> > 
> > 
> > Hmm... I really wouldn't. The SHAs are still unique and defining in themselves, no?
> > And the PRs are still there if one needs to dig through them. It should still be more efficient to search through them using GH's search functionality than referencing a commit SHA? Or?
> 
> I can jump back on and show you what I mean (if you see this within the next 5 mins) otherwise we can discuss tomorrow

Let's discuss tomorrow

**Comment by ml-evs** [comment]
Superseded by #365 (discussion at #366).

**Pull request closed without merging**
