### PR TITLE
Update mcloud provider index base URL

### PR DESCRIPTION
**Pull request by CasperWA**
NOTE: This is against `master` branch, not `develop`.

### CODE REVIEW

**Comment by ml-evs** [comment]
Do you mind if I hijack this to add our new info too?

**Comment by CasperWA** [comment]
> Do you mind if I hijack this to add our new info too?

Sure, go ahead! But remember the URL has to point to the base URL of an [Index meta-database](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.rst#index-meta-database).

> EDIT: just realised that providers.json is quite different in develop, so will make my changes there instead.

Actually, `providers.json` has not changed between `master` and `develop`.

**Comment by ml-evs** [comment]
> Sure, go ahead! But remember the URL has to point to the base URL of an [Index meta-database](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.rst#index-meta-database).

Now I've seen your PR adding the index meta db, I'll wait until I have my server running with that before adding (can be a separate PR).

> > EDIT: just realised that providers.json is quite different in develop, so will make my changes there instead.
> 
> Actually, `providers.json` has not changed between `master` and `develop`.

Weird, no idea what version I had locally then (must be from an old fork).

**Comment by ml-evs** [comment]
Given how smoothly updating to the routing system in optimade-python-tools has gone, could I get write access to this branch @CasperWA so I can add my implementation?

**Comment by ml-evs** [comment]
Thanks @CasperWA , note I'm currently waiting for our SSL cert to refresh for https, http will work until then.

**Comment by merkys** [comment]
Why this PR is against `master`, but not `develop`?

**Comment by CasperWA** [comment]
> Why this PR is against `master`, but not `develop`?

Because I would like to have them in the `providers.json` ASAP :smiley: Not just when we at some point decide to update the version.

**Comment by merkys** [comment]
> Because I would like to have them in the `providers.json` ASAP smiley Not just when we at some point decide to update the version.

Makes sense :)

**Comment by CasperWA** [comment]
> Thanks @CasperWA , note I'm currently waiting for our SSL cert to refresh for https, http will work until then.

If you want to put in the https URL right away, it should be fine, although broken until available, naturally, but otherwise you would need to create another PR.
Do you also want to keep the description empty?

**Comment by merkys** [comment]
Actually, I'm a little hesitant about modifications to `master`. `README.md` states that `master` presents the *stable* version of the specification, and *stable* means immutable. Thus by defining new database-specific prefixes we're theoretically requiring the adopters of v0.10.0 to update their implementations, especially if #162 gets merged. Or am I being too nitpicky?

**Comment by CasperWA** [comment]
> Actually, I'm a little hesitant about modifications to `master`. `README.md` states that `master` presents the _stable_ version of the specification, and _stable_ means immutable. Thus by defining new database-specific prefixes we're theoretically requiring the adopters of v0.10.0 to update their implementations, especially if #162 gets merged. Or am I being too nitpicky?

Ah, @ml-evs has added a new provider-prefix with `odbx`? Yeah, that could be problematic. I would argue that, as the spec is now (in `master`), the two things are decoupled. Ideally, I think `providers.json` and the spec should _always_ be decoupled, since `providers.json` is simply _our_ (i.e., Materials-Consortia's) database provider-specific prefixes. Other consortia or implementers using our spec may use another `providers.json`.
At least I believe this is the intent going forward from previous discussions on this issue between @rartino, @merkys, @sauliusg, and I, maybe more?
Summa summarum, I think it should be fine to update `providers.json` in `master` and add new database provider prefixes as long as the consortium agrees. It should not affect the spec.

**Comment by ml-evs** [comment]
Happy to delay my changes to another PR if that's preferable, just force push over my commits @CasperWA.

**Comment by CasperWA** [comment]
@merkys (and @ml-evs) I have removed @ml-evs's contribution and instead found that there were some indentation issues in two lines.
Most importantly, I have removed the `/index` for the `exmpl` provider. This is _needed_ since no OPTiMaDe implementations, index or otherwise, is allowed to have such a base URL as was written previously. The `index` and `optimade` may be switched, but I think it's better just to remove `index` all-together, what do you think?

**Comment by CasperWA** [comment]
> Happy to delay my changes to another PR if that's preferable, just force push over my commits @CasperWA.

Done. Sorry.
I would make a new PR if I were you, start by making it towards `master` as well, and then we can discuss whether that is correct or not in said PR.

**Comment by CasperWA** [comment]
@merkys are you okay with updating `providers.json` in master for information under existing providers?

**Comment by merkys** [comment]
> @merkys are you okay with updating `providers.json` in master for information under existing providers?

I'm OK, as long as everyone else is fine with touching the `master`. Probably there's no need to be so nitpicky prior to v1.0 release.

Although I'm leaning towards decoupling `providers.json` from the specification for the same reason, still a centralized registry will be needed to keep track of the reserved prefixes.

**Comment by CasperWA** [comment]
Since we have already 4 approvals on this PR, and it doesn't touch anything other than `provider.json`, I will merge it.

**Comment by CasperWA** [comment]
> Although I'm leaning towards decoupling `providers.json` from the specification for the same reason, still a centralized registry will be needed to keep track of the reserved prefixes.

I agree. And I think the centralized registry should be kept elsewhere.

**Comment by rartino** [comment]
How about we just create another repo under Materials-Consortia named providers. In that repo we replicate the URL structure of an index server, with and without major API version number URLs, and commit providers.json there (i.e., practically it will be under two paths with and without version number). The github raw URL becomes our "master" index server for now.

**Pull request merged**
