### PR TITLE
Fixing the issue template

### PR DESCRIPTION
**Pull request by giovannipizzi**
Adding also a CONTRIBUTING file and a Pull Request template

I think we want only one issue template, the one added in #40
was not appropriate as it was showing useful only to have more than
one different template.

### CODE REVIEW

**Comment by rartino** [comment]
The wiki document being linked here is a great resource to help people contribute.

But, should it reference the email list directly, with a linked email address? Right now I believe only people on that list can email the list. Should we be more vague along the lines of:
"Issues that require broad discussion will have to be discussed at the OPTiMaDe internal mailing list before they can be accepted."

**Comment by giovannipizzi** [comment]
Sure, for me it's ok, anyway I think it was @ltalirz who added additional info including the email address so I let him answer.
As the wiki content can be edited independently of this PR (unless we want to write some text directly into the template), if you agree we can proceed with approving merging this while we continue the discussion on the wiki page content.

**Comment by rartino** [comment]
Well, perhaps it slightly affects how this should be formulated:

  "If your pull request requires discussion, alert the mailing list after you created the pull requests as described in the link above."

How about:

"If your pull request requires discussion, make sure the OPTIMaDe developer list is alerted (for more info see the link above.)"

**Comment by giovannipizzi** [comment]
Done

**Comment by ltalirz** [comment]
@rartino Let me know if you'd like me to remove the optimade mailing list from the wiki as well - for me it was more a practical thing in order for people not having to look it up.
But fine to remove it if you prefer.

**Comment by rartino** [comment]
@ltalirz Given that it isn't a public list, I think it makes sense not to explicitly list it on the public wiki; I foresee frustration coming out of that. But I'm not entirely sure how to best rewrite the text.

Perhaps: "If your issue requires broad discussion, it needs to be discussed on the OPTiMaDe developer mailing list before any actions can be taken. (If you are not on this list, please contact one of the [repository contributors](https://github.com/Materials-Consortia/OPTiMaDe/graphs/contributors) to bring your issue to the lists attention.)

And further down: "send out another mail to the mailing list to make sure everybody can check the PR and give comments." -> "make sure the OPTIMaDe developer email list is alerted again to bring in feedback on the PR."

**Comment by ltalirz** [comment]
@rartino Done (with minor adjustments)

**Pull request merged**
