### PR TITLE
Add URLs and descriptions for the COD and the TCOD

### PR DESCRIPTION
**Pull request by merkys**
URLs and descriptions added for COD and TCOD.

### CODE REVIEW

**Comment by merkys** [comment]
> Are the base URLs pointing to index meta-databases as required?

Not yet. I plan to roll out the index meta-database this week.

> If you want this update to be available ASAP, you should probably point it towards `master` branch instead :)

As discussed in #214, I'm fine with `develop` :)

**Comment by CasperWA** [comment]
> Not yet. I plan to roll out the index meta-database this week.

May I recommend you try out our new-fangled [index meta-database implemention in `opimade-python-tools`](https://github.com/Materials-Consortia/optimade-python-tools/pull/103)? :smile:

**Comment by merkys** [comment]
> May I recommend you try out our new-fangled [index meta-database implemention in `opimade-python-tools`](https://github.com/Materials-Consortia/optimade-python-tools/pull/103)?

While I'm really interested in `opimade-python-tools`, I'm going to implement this myself ;) I think of this as yet another test for the specification :)

**Comment by CasperWA** [comment]
This should be closed here and remade in `Materials-Consortia/providers`.

**Comment by rartino** [comment]
Now that #222 is merged, this needs to be closed and refiled against `Materials-Consortia/providers`.

**Comment by merkys** [comment]
> Now that #222 is merged, this needs to be closed and refiled against `Materials-Consortia/providers`.

Right, closing.

**Pull request closed without merging**
