### PR TITLE
Fixing docker to run the tests

### PR DESCRIPTION
**Pull request by fekad**
The quick fix to installing the missing dependencies. On a non-ubuntu/debian machine, the docker still seems to be the best way to run the tests.

### CODE REVIEW

**Review by merkys — APPROVED** [review]
`curl` and `jq` seem to be used by `tests/scripts/validate_swagger.sh`. I was not aware they are missing from the Dockerfile, but it seems legit.

**Review by ml-evs — COMMENTED** [review]
Sorry for missing this at the time, this lgtm.

**Review by ml-evs — APPROVED** [review]

**Comment by fekad** [comment]
@ml-evs Please feel free to merge it because I do not have write access to this repository anymore...

**Comment by ml-evs** [comment]
> @ml-evs Please feel free to merge it because I do not have write access to this repository anymore...

Done! Did you remove yourself from the org? I can re-add you if you like

**Pull request merged**
