### PR TITLE
Minor rst updates - no content changes

### PR DESCRIPTION
**Pull request by CasperWA**
This PR fixes minor typos and layout issues found in `optimade.rst`.

I have made it a branch in the original repository, so that everyone can contribute fixes to the branch, i.e., this PR, if one should come upon any not already fixed here.
However, it is _not_ allowed to create actual content changes - _only_ **formatting** or **typos**.

This may be merged anytime between the time you are reading this, and when people feel enough "minor" fixes have been made.

### CODE REVIEW

**Comment by rartino** [comment]
Would it be OK to push into this branch edits that addresses #155? Those would be a bit bigger, but they are without content changes.

**Comment by CasperWA** [comment]
> Would it be OK to push into this branch edits that addresses #155? Those would be a bit bigger, but they are without content changes.

For sure. So long as there are no content (or interpretation) changes, it seems ideal to incorporate as much as possible in this single PR.

**Comment by rartino** [comment]
To do my edits I had to merge in the recent state of the devel branch, so I did that.

I've pushed some rather large edits that are (according to my interpretation) not "content changes".

Most importantly I've moved around sections/subsections in sections 3, 4. The order and overall structure should now IMO be much more logical, but let me know if anyone disagrees. (The easiest way to see what has happened is to look at the whole document and check the rendering of the table of contents.)

**Comment by rartino** [comment]
@CasperWA I refrain from deleting the branch `minor_rst_updates` since you set it up. However, if you are happy with the merge, please delete it.

**Comment by CasperWA** [comment]
Removed. Thank you for your work with this @rartino and @merkys

**Pull request merged**
