### PR TITLE
Making a pair of intended RFC2119 keywords uppercase

### PR DESCRIPTION
**Pull request by merkys**
There were a couple of improperly typeset RFC 2119 keywords (`*optional*` instead of `OPTIONAL`).

### CODE REVIEW

**Comment by merkys** [comment]
> [ ] section 3.3.4. Unset optional properties
> 
>     * All cases of optional here should be OPTIONAL, even the title, I think?

Hmm... I'm not sure. I feel that *optional property* is a term definition here.

**Comment by merkys** [comment]
>     * [ ]  section 3.3.4. Unset optional properties
>       
>       * All cases of optional here should be OPTIONAL, even the title, I think?

Not sure whether the *optional propery* is not a term by itself here.

>     * [ ]  section 4.4. Links endpoint
>       
>       * There is one sentence that starts like "Alternatively, it MAY optionally ..." Should be OPTIONALLY.

I think "MAY" already specifies the level of requirement here. Probably "optionally" might be removed without changing the meaning.

>     * [ ]   section 5.2. The Filter Language Syntax
>       
>       * Found under the sub-section Comparisons of multi-valued properties, for a sentence starting: "The construct is optional ..." Should be OPTIONAL.

Fixed.

>       * Also under the Optional filter features (last sub-section). Several cases, including the title, where it should be OPTIONAL.

Fixed.

>     * [ ]  Appendix 2: The Filter Language EBNF Grammar.
>       
>       * Simply remove "optional" from `ValueZip`, making the comment similar to other comments here.

Removed.

**Comment by CasperWA** [comment]
> * [ ]  section 3.3.4. Unset optional properties
>   
>   * All cases of optional here should be OPTIONAL, even the title, I think?
>>
>> Not sure whether the *optional propery* is not a term by itself here.

Not sure either. I am willing to leave this out now, but I don't know when it would be considered again in the future, if at all, i.e., we should probably figure it out now. Calling @ctoher to answer this :)

> * [ ]  section 4.4. Links endpoint
>   
>   * There is one sentence that starts like "Alternatively, it MAY optionally ..." Should be OPTIONALLY.
>>
>> I think "MAY" already specifies the level of requirement here. Probably "optionally" might be removed without changing the meaning.

Several places (if I remember correctly) we have MAY OPTIONALLY. But I am okay with removing optionally/OPTIONALLY completely here.

**Comment by CasperWA** [comment]
> (I have a feeling that after the workshop one or more of us will have to proofread the compound document anyway, so it seems to me that we can try to catch the rest at that point, if there are any.)

Good point. With this I only request a stance from @merkys on the second remaining change suggestion (section 4.4. MAY OPTIONALLY, versus simply MAY).

**Comment by merkys** [comment]
> Several places (if I remember correctly) we have MAY OPTIONALLY. But I am okay with removing optionally/OPTIONALLY completely here.

Converted all "MAY OPTIONALLY" -> "MAY".

**Pull request merged**
