### PR TITLE
Add CC-BY 4.0 license for the specification

### LINKED ISSUE #111: Add license to specification
as discussed I plan to add the Creative Commons 4.0 BY license,
potentially with separate suggestions pointing out that optimade.org is the official optimade organisation and that name clashes should be avoided.

I'll also try to give a look to what other specification bodies do for such cases.

### PR DESCRIPTION
**Pull request by merkys**
Looks like the discussion in #111 have quieted down a little, and CC-BY seems to be an option suitable for the most of people there.

Sorry for spamming with review requests. Nevertheless, I couldn't ask reviews from everyone due to apparent limit of 15 reviewers.

Fixes #111. (Sorry @ltalirz for stealing your PR)

**Edit**: please **don't merge** this PR until all the parties have agreed with the proposal.

### CODE REVIEW

**Comment by ltalirz** [comment]
Maybe add a short section about the license to the README, mentioning that it applies to the specification document only?

**Comment by merkys** [comment]
> Maybe add a short section about the license to the README, mentioning that it applies to the specification document only?

Is there a reason against covering all files by the same license?

**Comment by merkys** [comment]
> If we ever include foreign files that are under different compatible F/LOSS licenses, we'll have to write a note or readme; I guess Andrius can explain better how this is handled in Debian.

Having a single all-covering license seems to be a common practice in the F/LOSS world, and I believe this could be easily applied to documents such as specifications. Should we need to add 3rd party documents/software, we could place them in a separate directory with their licenses, and place a note in README noticing about them.

Having an all-covering license simplifies things a lot. For example, if only `optimade.rst` is covered by CC-SA, it will have to be distributed without the `AUTHORS` file. Moreover, derived projects wouldn't be able to use the testing system, etc.

**Comment by CasperWA** [comment]
> Maybe add a short section about the license to the README, mentioning that it applies to the specification document only?

This seems like the most careful / secure approach, right?
Providing the license _only_ for the spec allows immediate re-usage of the spec, while allowing us to consider a bit more what license should be on our test files, `providers.json`, etc.

On the other hand, it may just postpone the real decision further, leaving us with another long period on non-decision...

**Comment by CasperWA** [comment]
Tagging @csadorf here to give him a chance to add his thoughts, if any, since he was very involved lately in the issue discussion.

**Comment by rartino** [comment]
From a formal copyright perspective, we still need approvals of @ctoher, @fekad, @coreyoses, @ml-evs, @gmrigna, @fawzi, and @muhrin as those have contributed to the repository but not yet approved this PR. I'm tagging them here in the hope that they'll see this, visit this github page, and do the approval.

**Comment by rartino** [comment]
One more attempt to ping the missing people: Hello @ctoher, @fekad, @coreyoses, and @fawzi: please log into github and approve the new repository license! It'll only take a minute!

**Comment by coreyoses** [comment]
Thanks for the poke @rartino. I finally sat down to read about the license.

**Comment by rartino** [comment]
I've now sent personal emails to the few people remaining in hope that we get the final approvals in time for the Dec 20 deadline.

**Comment by rartino** [comment]
@merkys My interpretation is that everyone who has committed to the repository now has approved the licensing. Please check that, and then feel free to press the big green button.

**Comment by merkys** [comment]
OK. Thus a last call: if no one is against, I will merge this PR on Thursday 19th, 08:00 UTC.

**Pull request merged**
